### ISSUE TITLE
MVP Todo

### ISSUE THREAD

**Issue by 10zinten** [OpenPecha/openpecha-toolkit#65]
- [x] Local id support for HFML serializer
- [x] Test whole HFML workflow:
     - [x] Add new annotation
     - [x] Edit anntation
     - [x] Delete annotation
- [x] CLI command for:
     - [x] HFML formatter
     - [x] HFML serializer
     - [x] Ebook serializer
- [x] Github Action
     - [x] HFML format and serialize
     - [x] opf Export
- [x] Entry point:
       1. HFML -> opf -> HFML with local-id

- [ ] Release and download
